### ISSUE TITLE
g++: error: unrecognized command line option ‘-m64’

### ISSUE THREAD

**Issue by jsbay** [serialport/node-serialport#2537]
### SerialPort Version

10.4.0

### Node Version

v16.17.0

### Electron Version

v17.4.11

### Platform

Linux linaro-alip 4.19.219 #334 SMP Mon Jul 18 13:48:02 CST 2022 aarch64 GNU/Linux

### Architecture

arm64

### What steps will reproduce the bug?

1. download electron-serialport demo from https://github.com/serialport/electron-serialport
2. `yarn`
3. `yarn start`, it work well
4. add electron-builder: `yarn add electron-builder@^23.3.3 --save-dev`
5. add `electron-builder.yml` like:
```yml
productName: electron-serialport
appId:  jsbay.com.app
copyright: copyright

directories: 
  output: build

electronDownload: 
  mirror: https://npm.taobao.org/mirrors/electron/

# linux: 
#   target: 
#     # - target: AppImage
#     - target: deb
#       arch:
#         - x64
#         - arm64
#         - armv7l
      # - target": "deb"
      # - arch: ["arm64", "armv7l", "x64"]
```

6. add scripts `"build": "electron-builder build"` to `package.json`
7. run `yarn build`

### What happens?

got error `g++: error: unrecognized command line option ‘-m64’`
<img width="892" alt="image" src="https://user-images.githubusercontent.com/26533192/189016592-cbebfe3e-d416-4d67-9466-4491dccf4889.png">

### What should have happened?

wish to pack success
